name: localization
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.7
  photo_view: ^0.14.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  hooks_riverpod: ^2.3.10
  flutter_hooks: ^0.20.1
  image_picker: ^1.0.4
  firebase_core: ^2.16.0
  firebase_storage: ^11.2.7
  cloud_firestore: ^4.9.2
  uuid: ^4.0.0
  dismissible_page: ^1.0.2
  http: ^1.1.0
  external_path: ^1.0.3
  flutter_launcher_icons: ^0.13.1
  geolocator: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.2
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - env

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/icon_foreground.png"

