// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGaRq-njQZbmTBmYNKdRd5UscuIy5rl24',
    appId: '1:875382420227:web:205fdd62c91cf3ac2a2f36',
    messagingSenderId: '875382420227',
    projectId: 'localization-app-c5747',
    authDomain: 'localization-app-c5747.firebaseapp.com',
    storageBucket: 'localization-app-c5747.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfUVW-U6kKuQVQbDQgFcxFD87wj1pJXeU',
    appId: '1:875382420227:android:e6fb5874c4d371342a2f36',
    messagingSenderId: '875382420227',
    projectId: 'localization-app-c5747',
    storageBucket: 'localization-app-c5747.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATYVXloU1zQwpXsDX8yRVOo36uA_Fr4QA',
    appId: '1:875382420227:ios:ee7bdbc148e121032a2f36',
    messagingSenderId: '875382420227',
    projectId: 'localization-app-c5747',
    storageBucket: 'localization-app-c5747.appspot.com',
    iosBundleId: 'com.sakusaku3939.localization',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATYVXloU1zQwpXsDX8yRVOo36uA_Fr4QA',
    appId: '1:875382420227:ios:9b50365f8e51c9d52a2f36',
    messagingSenderId: '875382420227',
    projectId: 'localization-app-c5747',
    storageBucket: 'localization-app-c5747.appspot.com',
    iosBundleId: 'com.sakusaku3939.localization.RunnerTests',
  );
}
